---
name: Create github release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    name: Create GitHub release
    if: ${{ github.repository_owner == 'voxpupuli' }}
    steps:
      - name: Create Release Page
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --repo ${{ github.repository }} ${{ github.ref_name }} --generate-notes
